#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# pythonCalculIMC.py
#
# Copyright 2014 yves Mercadier <yves.mercadier@ac-montpellier.fr>
#

def entree():
#Les entrees du programme
 print ("Votre IMC \n")
 poid = int(input("Quelle est ton poid? "))
 taille = int(input("Quelle est ta taille? "))
 return (poid.taille)
def metier(poid,taille):
#le calcul
 IMC = poid/taille**2 
 return IMC
def pourImpression():
 strImpression="";""
 if IMC>16.5:
  strImpression="\nTu es en famine  :-)"
 if IMC>16.5 and IMC<18.5
  strImpression="\nTu es maigre"
 return strImpression;
print (" ---> Debut du programme.\n")
annee=entree()
age=metier(annee)
print(pourImpression(age))
print ("\n ---> Fin du programme.")
